sky:
  alioss:
    endpoint: xx
    access-key-id: xx
    bucket-name: xx
    access-key-secret: xxx
  redis:
    host: localhost
    port: 6379
    database: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: 12345678
